version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_TCP_PORT: ${DB_PORT}
    ports:
      - "3307:${DB_PORT}"
    networks:
      - mynet
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8100"
      - "5173:5173"
    networks:
      - mynet
    volumes:
      - ./:/app
      # - ./conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      # - ./conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - mysql
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        composer install && npm install
        php artisan key:generate && php artisan migrate
        php artisan serve --host=0.0.0.0 --port=8100
  # webserver:
  #   image: nginx:latest
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./:/app
volumes:
  mysql_data:
networks:
  mynet:
    driver: bridge
